apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  labels:
    project: {{ .Chart.Name }}
    name: fluent-bit
spec:
  selector:
    matchLabels:
      name: fluent-bit
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        project: {{ .Chart.Name }}
        name: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.7.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.fluentbit.port }}
          protocol: TCP
        volumeMounts:
        - mountPath: /fluent-bit/etc/fluent-bit.conf
          name: fluent-bit
          subPath: fluent-bit.conf
      volumes:
      - name: fluent-bit
        configMap:
          name: fluent-bit
---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  labels:
    project: {{ .Chart.Name }}
    name: fluent-bit
spec:
  type: LoadBalancer
  selector:
    name: fluent-bit
  ports:
  - protocol: TCP
    port: {{ .Values.fluentbit.port }}
    targetPort: {{ .Values.fluentbit.port }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  labels:
    project: {{ .Chart.Name }}
    name: fluent-bit
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush       1
        Log_Level   info
        Chunk_Size  512KB
        Buffer_Size 512MB

    [INPUT]
        Name        Forward
        Listen      0.0.0.0
        Port        {{ .Values.fluentbit.port }}

    [OUTPUT]
        Name                            kafka
        Match                           kafka.*
        Brokers                         {{ .Values.kafka }}
        Topics                          word-cloud
        Topic_Key                       topic
        Message_Key_Field               key
        rdkafka.retries                 3
        rdkafka.log.connection.close    false
        rdkafka.request.required.acks   1
