apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  entityOperator:
    topicOperator: {}
  kafka:
    config:
      inter.broker.protocol.version: "2.8"
      log.message.format.version: "2.8"
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
    - name: lb
      port: 9096
      tls: true
      type: loadbalancer
    - configuration:
        useServiceDnsDomain: true
      name: plain
      port: 9092
      tls: false
      type: internal
    replicas: 1
    storage:
      type: ephemeral
    version: 2.8.0
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
